---
kind: pipeline
type: docker
name: push-latest-build
steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: lblod/delta-producer-json-diff-file-publisher
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - master
---
kind: pipeline
type: docker
name: release
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: lblod/delta-producer-json-diff-file-publisher
    dry_run: true
    purge: true
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: lblod/delta-producer-json-diff-file-publisher
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  event:
    - tag
---
kind: secret
name: docker_username
data: jVm/ytzB0BGWt48Xr1UsFPnDmrioda4tptFiN8Lr4Q4pRg8aAkkcMQ==
---
kind: secret
name: docker_password
data: UK83lNXBl1WMKf2wNh0L6EfP0WgMkhkYRaN4/jGnYhT1r0aYNaRMpjwhOObq8UZy62AXDmOgVbSFx0Xf7JZBkA==
---
kind: signature
hmac: 9d211812f07bd299b8345fb2b88b9c824b70002cb01791996002d6bf39a42202

...
